### ISSUE TITLE
Unable to access InfluxDB REST API from c#

### ISSUE THREAD

**Issue by sameerbetageri** [pootzko/InfluxDB.Net#1]
I have installed InfluxDB nuget package using
Install-Pckage influxDB.Net-Main

I am getting error that namespace or name InfluxDB could not be found.

Following is my screen shots of error. Any help in this regard is very much appreciated.
![srn1](https://cloud.githubusercontent.com/assets/19279489/20783258/ac763af4-b7b8-11e6-8587-aad9af7ed8e0.png)

**Comment by sameerbetageri** [comment]
@pootzko

**Comment by tihomir-kit** [comment]
Hey man,

this is just and old fork of that repo.. This is the correct github page for that package:
https://www.nuget.org/packages/InfluxDB.Net-Main/
https://github.com/ziyasal/InfluxDB.Net
